### ISSUE TITLE
Never Enough Sources? Guild Wars 1

### ISSUE THREAD

**Issue by ChthonVII** [kcat/dsoal#28]
Still trying to get DSOAL and Guild Wars 1 to play nicely together. The latest, hopefully last, roadblock is a giant pile of "0074:err:dsound:DSBuffer_SetLoc Out of software sources" in the log, accompanied by a bunch of missing sounds in-game.

In alsoft.ini, I've tried cranking things up to "sources = 4096, slots = 256," and yet the issue persists. So I'm starting to wonder if there's a more fundamental problem here.

Is my presumption correct that the "sources" knob in the ini is relevant to this error message?

What's a sane upper bound for these values?

4096 sounds like an awful lot of sources, more than I'd expect the game to actually use at one time. Is it possible things aren't getting freed when they should be? Any guidance for a hacky method to identify and free stale sources proactively?

[Edit: May have answered my own question: Looks like DSOAL has a hard-coded limit of 512 sources in dsound_private.h, is that correct? If so, what horrible things will happen if I increase that?]

**Comment by kcat** [comment]
> [Edit: May have answered my own question: Looks like DSOAL has a hard-coded limit of 512 sources in dsound_private.h, is that correct? If so, what horrible things will happen if I increase that?]

Nothing too terrible on its own; it'll generate more sources and use a bit of memory, but if the sources aren't actually played simultaneously, nothing beyond that. If they are played, it would increase CPU processing for mixing.

But the issue here is a bit more perplexing. DSOAL allocates up to 512 sources, as you say, and will segment them into 256 "hardware" sources (which is fairly generous for hardware DSound capabilities) and 256 "software" sources (doubling the amount of total playable sounds, and also what software OpenAL normally provides). More over, the actual sources are only taken and counted as in-use when a DSoundBuffer needs one, which is either on DSoundBuffer initialization (if the LOCDEFER flag isn't set) or when first played. On top of this, unless the game is explicitly requesting software buffers, it will use up "hardware" sources first, so to be "Out of software sources", it has to have 512 buffers all allocated and prepared to play if not already played (even if explicitly requesting software buffers, it has to have 256 of them before that error would trigger).

As far as I can surmise, there's three possibilities:

1) There's a problem somewhere that's causing the game to use more buffers than normal, and not release them when it should,

2) Native DSound allows creating many more buffers than DSOAL can, which the game depends on, or

3) There's some condition in which a DSoundBuffer should be able to lose its source, allowing it to be used by other buffers in the mean time.

`1` would be difficult to track down, as there's no telling what logic the game may be using to know when to release its buffers. `2` could be partly tested by making a test app and querying those values from the DSound API, though to properly test would require real hardware DSound (which hasn't been available since Windows XP) since that's what DSOAL is emulating. `3` would also be difficult to test, though it might be possible to make a test app to watch DSound's behavior when it's stressed with a whole bunch of buffers. Beyond this, there's the `4`th possibility that the game simply doesn't work with hardware DSound, and by reporting it as available the game is using a buggy codepath that would be a problem even on native Windows (though this isn't terribly likely if the game is expected to work on Windows XP; I don't know what Windows version the game was released for).

Unfortunately the only testing I'd be able to do is with Wine, which may not have accurate behavior in this regard (it just does what needs to be done with itself to make apps happy, and doesn't really concern itself with exactly replicating native behavior). For its part, Wine seems to allow an infinite number of software buffers, though I can't say if this is proper behavior or if `3` would come into play on real Windows. Wine also reports 16 hardware buffers, though this is typically too low for apps to be happy with and will almost always fall back to non-hardware codepaths.

**Comment by ChthonVII** [comment]
Thank you very much for your reply!

I tried increasing MAX_HWBUFFERS to 512 and MAX_SOURCES to 1024 (and added another "else if" block at line 399 of dsound8.c so it can still get down to 128), and it passed a short test. I need to find time to do a more extensive test to see if that really fixes it for all cases. Keeping my fingers crossed that it was really that easy.

GW1 was originally released for WinXP in 2005. However, it got its last expansion in 2007 (a few months into the Win Vista age) and several patches in later years, so it's possible that the dsound code path got broken somewhere along the way.

Something perhaps relevant from my earlier testing: By design, the game goes silent during the load screens when changing zones. I'd think it'd make sense for the game to release all its buffers during this silent period. But I can tell that's not happening since I can reliably get a particular missing sound by doing a whole lot of noisy stuff, then changing zones, then immediately doing something to generate that sound for the first time. (The same sound plays normally if I just load into the game and immediately do something to generate it.) This behavior would be consistent with the game failing to properly release its buffers. Though it could also be consistent with a scheme of releasing stale buffers every X seconds, or after X seconds, or only when 1000 buffers are in use, or whatever. So it's not determinative.

Since I personally use Wine too, my primary concern is getting it working in Wine. Of course it would be nice to fix it for everyone on Windows as well, but "working in Wine" is my main target.

**Comment by mirh** [comment]
Take note that openal on linux/wine is an extra layer of mystery
https://bugs.winehq.org/show_bug.cgi?id=40898

**Comment by ChthonVII** [comment]
Nope. MAX_HWBUFFERS to 512 and MAX_SOURCES to 1024 didn't hold up in a longer test. I'll try moving it up to something very large. If that doesn't work, I guess it's time to start looking for a hacky way of releasing the buffers the program isn't.

**Comment by ChthonVII** [comment]
Passed a short test by coercing LOCDEFER when a software buffer is explicitly requested. Still need to implement safety checks in case there are as-yet-undiscovered circumstances where the program will call something on these buffers that expects source to be non-NULL. And then some longer tests.

This approach seems promising right now. If it pans out, I suppose it's going to need to go in a fork, since other programs might be using explicitly-requested software buffers for more than just storage.

**Comment by kcat** [comment]
> So... what's going on here? It's explicitly asking for software buffers, and then never playing them. Is it plausible that the program is just using software buffers to store its audio data for faster copying to a hardware buffer when needed? (Would that really be faster? Would it have been faster in 2005?) How would I go about testing this theory?

That would be very odd. I wouldn't put it past a commercial game doing something that crazy, but it certainly doesn't look like an optimal way to store audio data before using it on-demand in hardware. Maybe it helped somewhat simplify storage and management on the app side, since the dsound buffer would hold the WAVEFORMATEX struct and the buffer length for you, but it wouldn't really be much more work to roll a custom struct that does the same with less overhead (no need to track buffer parameters like its volume/pitch/offset/etc which are never used).

> Assuming that's what's going on, could I get away with coercing LOCDEFER when a software buffer is requested?

Probably not LOCDEFER itself, but implementing similar behavior of not taking a source until it's actually needed to play, perhaps. Making software buffers more aggressive with getting rid of their source after it's finished. Perhaps even lying and say software buffers play and immediately stop when they can't get a source, rather than error.

**Comment by ChthonVII** [comment]
Did a more proper implementation of deferred source assignment when a software buffer is explicitly requested ([code](https://github.com/ChthonVII/dsoal-GW1/commit/5d1e66ff5cc1ceb79acd5ee1ac24d84f2f8c16c8)). It appears to be working. I was able to test it with a ~1.5hr session, during which I didn't notice any missing sounds, and which produced a clean log file. So I think we can call this fixed, and fully working with Guild Wars.

During that 1.5hr test, never once was the deferred assignment code reached. It appears the program really is just using those software buffers as storage. At least, that's the only explanation I can think of.

I'm doubtful this is suitable for a pull request. I worry that the deferred source assignment might increase latency or otherwise hurt performance for other programs that actually _play_ the software buffers they've explicitly requested. I'd rather make Guild Wars people live with using a fork than potentially degrade things for other people. Though maybe that should be reconsidered if several other games turn up with the same idiosyncratic approach to software buffers.

@mirh: Thankfully I'm not experiencing too much extra trouble from wine. The only issue I'm having is that it absolutely refuses to load dsound.dll from the program directory, no matter what I do with the relevant reg entries. But putting it in system32 doesn't pose a problem here since this is a dedicated wine prefix anyway.

**Comment by mirh** [comment]
Reg entries.. meaning setting to native or built-in?
Anyway, did you check wine/staging dsound sources for ideas?

**Comment by ChthonVII** [comment]
> Reg entries.. meaning setting to native or built-in?
[This collection of CLSID reg entries](https://www.indirectsound.com/registryIssues.html) that many people seem to agree is necessary to get Win8/10 to use a dsound.dll from the program directory. Indeed, I did have those set, and pointed to sys32, but changing it doesn't seem to matter in wine; it's still using dsound.dll from sys32 come hell or high water.

> Anyway, did you check wine/staging dsound sources for ideas?
Nope. I'm not bothered by it enough to go digging into wine's source for answers. Since I'm using a dedicated wine prefix for this game, it doesn't bother me much to just replace the system dll.

**Comment by kcat** [comment]
On Wine, you might need to set a DLL override in `winecfg`. In that GUI's Libraries tab, if `dsound` isn't already in the Existing overrides, select it using the drop-down list and click Add, then make sure it's set to "native, builtin". That will make it prefer a native `dsound.dll` it may find, and fall back to its own library if a native one can't be loaded. Alternatively, you can set the `WINEDLLOVERRIDES` env var to `"dsound=n,b"` when running the app with Wine for the same behavior (e.g. `WINEDLLOVERRIDES="dsound=n,b" wine app.exe`).

**Comment by ChthonVII** [comment]
> On Wine, you might need to set a DLL override in winecfg. In that GUI's Libraries tab, if dsound isn't already in the Existing overrides, select it using the drop-down list and click Add, then make sure it's set to "native, builtin". 

Thanks. Yes, I knew that. In fact I took it for granted that you have to set the dll override and so didn't bother to mention it. To make it explicit, I've had the dll override set to "native, builtin" in all cases.
