### ISSUE TITLE
DX SDK sample crashes with dsoal

### ISSUE THREAD

**Issue by mirh** [kcat/dsoal#40]
[Quick download](https://github.com/wongdu/refFoxuc/blob/master/Directx%20SDK%209.0c/Samples/C++/DirectSound/Bin/Play3DSound.exe)

**Comment by Kappa971** [comment]
This program doesn't seem official from Microsoft, what does it do? Maybe the problem is this program and not DSOAL or it takes advantage of some DirectSound function that is absent in DSOAL and crashes (like GTA San Andreas).

**Comment by mirh** [comment]
It's an official sample
https://github.com/walbourn/directx-sdk-legacy-samples/tree/main/DirectSound/play3dsound
If any it may be that they dropped all the directsound ones with the 2008 sdks, but still.

**Comment by ThreeDeeJay** [comment]
Can confirm. I don't know if there's anything useful but here's my log:
`3984:trace:dsound:load_libopenal Loaded dsoal-aldrv.dll
3984:trace:dsound:load_libopenal Found ALC_EXT_thread_local_context
3984:trace:dsound:DSOAL_DirectSoundCreate8 ((null), 00ED2B30, 00000000)
3984:trace:dsound:DSDevice_Create Creating device instance 006D7BE8
3984:trace:dsound:DS8_AddRef (006D7BE8) ref 1
3984:trace:dsound:DS8_Initialize (006D7BE8)->((null))
3984:trace:dsound:DSOAL_GetDeviceID (DSDEVID_DefaultPlayback, 000DF914)
3984:trace:dsound:DS8_Initialize Searching shared devices for {4ab7a8e2-da2b-4e63-a1f3-25c40571e13e}
3984:trace:dsound:DSShare_Create Creating shared device 006E4710
`
That's a nice find tho. Was there ever a 64-bit version of this or any other DirectSound3D benchmark app to test DSOAL x64?

**Comment by ThreeDeeJay** [comment]
Good news, turns out the DSOAL XP fork doesn't crash and even HRTF works (running Windows 10).
https://i.imgur.com/05BRFXJ.mp4
https://github.com/pachuco/dsoal-XP/tree/master/release

Properties don't seem to work tho, but they do in XP.
https://i.imgur.com/D24YAOj.mp4

btw in both XP and 10, all 3D algorithms sound identical.
But anyway, wonder how many broken games the XP fork fixes, and most importantly: if the relevant changes should be implemented in the master branch 🤔

**Comment by Kappa971** [comment]
With the recent changes in OpenAL Soft (EAX extensions) I don't think they are the only changes needed to DSOAL.

**Comment by mirh** [comment]
@pachuco

> That's a nice find tho. Was there ever a 64-bit version of this or any other DirectSound3D benchmark app to test DSOAL x64?

Yes? Updated source code is provided above, and x64 binaries were also provided in the original sdk.

**Comment by kcat** [comment]
> I think we need someone else who can help @kcat with the development (DSOAL seems pretty stuck at the moment).

I would like to get back to DSOAL after the next release of OpenAL Soft. That's taking a bit longer than expected because of PipeWire moving a bit slow along with a couple other things I'd like to have in for it.

**Comment by ThreeDeeJay** [comment]
Quick update: Still crashes on [DSOAL](https://github.com/ThreeDeeJay/dsoal/releases/tag/0.9.2) (https://github.com/kcat/dsoal/commit/a16c19fdbb6c56bbd40a011362da0742a49f6f35)

**Comment by kcat** [comment]
The executable doesn't seem to be available anymore, and I don't think I can build the sample from source (cross-compiling using MinGW-w64).

**Comment by ThreeDeeJay** [comment]
@kcat I made a backup [here](https://airtable.com/shrpPCOJwJiA8T8Hr/tbl3TyLn23qfBWZTz/viwEFl4VhIITjGRw1/reccsTaZ5LJrLzHKM). [Direct download](https://www.dropbox.com/s/z0n72k2y2z3e732/Play3DSound.zip?dl=1).

**Comment by kcat** [comment]
Hmm, it's not crashing here, using the latest DSOAL and OpenAL Soft (on Wine/Proton). Both the 32-bit and 64-bit versions work fine.

**Comment by ThreeDeeJay** [comment]
Interesting, perhaps it's related to the OS somehow.
I just tested again using the latest Github actions builds and on Windows 10 it still crashes, tho on my (mostly vanilla) Windows 11 virtual machine, it doesn't even run (no errors), even tho it works when DSOAL files aren't present.
Logs look very similar to https://github.com/kcat/dsoal/issues/40#issuecomment-1029738136
[dsoal_error-Win10.txt](https://github.com/kcat/dsoal/files/9050167/dsoal_error-Win10.txt)
[dsoal_error-Win11.txt](https://github.com/kcat/dsoal/files/9050168/dsoal_error-Win11.txt)

**Comment by kcat** [comment]
Might be related to the way it's handling COM during DSound device initialization. It initializes COM with `CoInitialize` to use `IMMDeviceEnumerator` and get an `IMMDevice` for the desired device. It then releases the enumerator and uninitalizes COM, but continues to query the `IMMDevice` for information. If the app already had COM initialized on the thread it's creating the DSound device with, it would be fine since COM initialization is reference counted (every init needs a deinit before it's fully deinitialized), but if it doesn't, the app could be crashing when trying to access the device after COM was uninitialized. Wine/Proton could be less sensitive to this than native Windows.

**Comment by kcat** [comment]
Try now with commit 910cf95edc7c36113e949fa073cae637d3b44557.

**Comment by ThreeDeeJay** [comment]
So far, so good 👌 https://i.imgur.com/nekEpEo.mp4

**Comment by ThreeDeeJay** [comment]
And to top it off, it also seems to fix #41 so I hope this means we won't have to resort to (ol' reliable, but still ol') https://github.com/pachuco/dsoal-XP anymore.
Tho I noticed there were some mentions of MMDevice and COM in https://github.com/kcat/dsoal/compare/master...pachuco:dsoal-XP:master so I wonder if there are other changes that might be worth merging 👀
