### ISSUE TITLE
Claw: Missing SFX and lower volume

### ISSUE THREAD

**Issue by RavenMacDaddy** [kcat/dsoal#53]
Homepage (unofficial): https://captainclaw.net/en/ 

Monolith no longer sells it, not even through something like GOG, and has no dedicated page for the game.

Instead a version with fixes for modern releases of Windows can be downloaded on the link above.  

--- 

Playing with the latest release which is based on OpenAL Soft 1.22 (unknown if this was an issue with previous versions of DSOAL), there are missing SFX, like the trumpet when starting levels, or when picking up treasure.

The volume is also significantly lower compared to not using the wrapper.

---

Changed settings from defaults:

- Resampler quality: Cubic

---

OS: Windows 11 - 22H2 - 22621.1

**Comment by mirh** [comment]
Lower volume ***might*** actually be proper behaviour. Assuming the game was previously stuck to just using stereo, it may be that now a lot of the soundscape is getting spread to other channels. 
.. or it may be a bug idk (perhaps a variation of #51). 

> Playing with the latest release which is based on OpenAL Soft 1.22 

Not true. Dsoal is not "based" on any specific openal-soft version. It uses whatever it finds. 
(even though since fe2978f17b949bdf6d013968635fe9dcc69b2492 you could say it's "*more* based" on openal-soft)

> unknown if this was an issue with previous versions of DSOAL

Test it!
You can try older versions/mixes of both things if you have time to spare. 
http://vaporeon.io/hosted/dsoal-builds/
https://openal-soft.org/openal-binaries/

**Comment by RavenMacDaddy** [comment]
Interesting, it does work with r422, the previous release.

**Comment by mirh** [comment]
If you could use the latest oal from [here](https://github.com/kcat/openal-soft/actions) in your testing, it'd be great. 
The biggest change [between](https://github.com/kcat/dsoal/compare/ffab58c75457e182951615af54690b21be23db3b...75f88e1bd9231d128ff38d99339680a86c45ccfb) r422 and r430 was the one I mentioned above, which caused lots of regressions still being addressed.

**Comment by RavenMacDaddy** [comment]
The latest artifact CI #224: Commit [cdd9a21](https://github.com/kcat/openal-soft/commit/cdd9a2177c0400ee3d894cd24fe43abb1e7b703c) at the time of writing works, however still only with dsound.dll from r422.

**Comment by Kappa971** [comment]
Here is information about this game that I didn't know at all: https://www.pcgamingwiki.com/wiki/Claw
We are talking about a game from 1997, it is probably one of the first Windows games along with Road Rash, Earthworm Jim, Pitfall. What's the point of using DSOAL in these games? I doubt they have any kind of 3D audio nor EAX (the first Windows games I know to have EAX or 3D audio are Half Life and Unreal from 1998).

**Comment by mirh** [comment]
Yes, eax is a 1998 thing. So what?
Dsoal isn't just about. 

DS3D could have been already potentially available in [1996](https://en.wikipedia.org/wiki/DirectSound#DirectSound3D) (even though [miles](http://www.radgametools.com/msshist.htm) doesn't mention it explicitly in the changelog until almost the end of the century). And since 1997 sound card quality mattered (it's so weird to quote wikipedia).

**Comment by RavenMacDaddy** [comment]
I use it for Cubic spline resampling.

Especially old games are rough as-is.

As for surround, that would be weird considering it's a 2D action platformer.

**Comment by mirh** [comment]
Yes you are [right](https://www.vogons.org/viewtopic.php?f=5&t=69212#p786872). It [may](https://www.vogons.org/viewtopic.php?f=32&t=52414&start=1420#p1057351) or may [not](https://www.vogons.org/viewtopic.php?f=13&t=84&start=20) work already just with a MPEG-2 decoder actually, but this is outside the topic here.

**Comment by Kappa971** [comment]
> Yes, eax is a 1998 thing. So what?
Dsoal isn't just about.

mmh it definitely doesn't use DirectSound3D, probably just DirectSound (stereo audio, 2d) so, leaving out the higher quality resampling of DSOAL, it should work natively with Windows dsound.dll. It is however strange that there are some missing sounds with the latest versions of DSOAL, but i haven't tried this game.

> DS3D could have been already potentially available in [1996](https://en.wikipedia.org/wiki/DirectSound#DirectSound3D) (even though [miles](http://www.radgametools.com/msshist.htm) doesn't mention it explicitly in the changelog until almost the end of the century). And since 1997 sound card quality mattered (it's so weird to quote wikipedia).

Before 1998 I believe that no game uses 3D audio, indeed until 1997 there were still games for DOS. Also, one of the first cards to support this (Sound Blaster Live!) came out in 1998.

**Comment by mirh** [comment]
https://www.gamecareerguide.com/features/sound_and_music/090597/direct_sound.htm
Even if it's just to run the dx3 [samples](https://archive.org/details/directx3sdk) it should be an objective.

**Comment by kcat** [comment]
Given that it works with r422, which was made Nov 1st 2021, and not the latest version, and it doesn't use EAX, there's only a couple commits that could've really broken it.

Commit f7ce1f07ac8e28b275cecab94e349d1bd54d7c10 adds partial support for the VoiceManager extension that some apps want. It's primarily a no-op, but if the game uses it and is sensitive to what it may return, it could be causing the app to get confused and not play certain sounds.

Commit e7a82d4fda8502eef9f8aacaa207199917d94167 reduces the number of allocatable DSound buffers, from 256 "hardware" and 256 "software" buffers, to 128 of each. Some games didn't like having so many hardware voices, but if this game uses software buffers, it might be that 128 is too few. I don't know what native DSound does for the number of software buffers, but DSOAL might need the number of software buffers increased again.

**Comment by mirh** [comment]
https://github.com/kcat/dsoal/issues/23#issuecomment-1022119630 has build in-between the two points. 
Speaking of the number of sources specifically instead, I remembered https://github.com/kcat/dsoal/issues/28

**Comment by kcat** [comment]
> Speaking of the number of sources specifically instead, I remembered #28 ([here](https://stackoverflow.com/questions/2871905/openal-determine-maximum-sources#comment3487772_3203888) they pitch 1024 to be the magic amount?)

That seems to be referring to the number of OpenAL sources that can be created with their X-Fi card. Maybe that hints at the maximum number of DSound "software" buffers you could get with ALchemy (1024 total - 128 hw = 896 sw), or maybe it's unrelated and is just what they felt was good enough for OpenAL apps.

What's annoying is that OpenAL Soft could've had "infinite" (4 billion) sources and only limit the number to play as needed. But as [the answer in the stackoverflow question](https://stackoverflow.com/questions/2871905/openal-determine-maximum-sources/3203888#3203888) says,

> In practice if you're using a hardware based driver, just keep creating them until alGenSources fails.

For any apps that do that, there has to be a limit or else it can crash (if not hang the system from OOM). Even a really high default limit could cause memory waste if the app generates as many as it can but only uses a handful. So OpenAL sticks with the 256 default limit used by other implementations with the 'every source is playable' philosophy, and anything more needs to be requested by the app with the expectation it'll behave itself with the amount it asks to make.

That Guild Wars 1 issue may be a separate concern, since it doesn't actually play any of the software buffers it creates, so realistically it shouldn't need a source for them. Software buffers should probably handle sources more dynamically (get a source only when playing, give it back when not).

**Comment by kcat** [comment]
Commit e7bc895cbaaab466d09047710317774929e178c2 increases the number of software buffers (to 384), which should help with this case.
