### ISSUE TITLE
Is there a way to get log files through Wine?

### ISSUE THREAD

**Issue by mrmatteastwood** [kcat/dsoal#65]
Hey DSOAL team! I've been trying to enable DSOAL's logging feature while using Wine on Linux Mint 21. I added the following lines to my ~/.bashrc file:

export DSOAL_LOGLEVEL=3
export DSOAL_LOGFILE=dsoal-log.txt

I also executed the same two commands from the terminal before running Duke Nukem Manhattan Project with DSOAL. I did get 7.1 sound, so DSOAL worked. After exiting the game, I expected a file called, dsoal-log.txt in the same directory as dsound.dll, i.e., the DNMP root directory. But, nada. In fact, I searched my entire system and no such file exists.

Am I doing something wrong?

**Comment by kcat** [comment]
Hi,

If you don't specify a full path for `DSOAL_LOGFILE`, it's treated as relative to the current working directory at the time it opens the log file. Normally that means relative to the directory you run the game from, but it's possible the current directory is changed before the dsound DLL is loaded so the file ends up somewhere else. Or if the current working directory isn't some place that can be made into a Windows path (e.g. `C:\something\dsoal-log.txt`), that might cause an issue, or if the current directory is set to some place that you don't have write access to as a user.

I'd first try specifying a full path for the logfile name, like `DSOAL_LOGFILE=C:/dsoal-log.txt`, somewhere you know you have write access to, and see if it works then. If not, you can try leaving `DSOAL_LOGFILE` unset and redirect stderr instead, with a command like `wine whatever.exe &>dsoal-log.txt`.

**Comment by mrmatteastwood** [comment]
Thanks @kcat! Using C:/ for the path did the trick.

**Comment by mirh** [comment]
#25
I really feel like there's so many people that would benefit of the log being written by default

**Comment by mrmatteastwood** [comment]
I agree. IndirectSound does it and I always found it very useful. Would be an awesome default feature to have!

**Comment by kcat** [comment]
> I really feel like there's so many people that would benefit of the log being written by default

The main issue is that the full trace log is extremely large, since it traces each call with its parameters. It can easily grow to hundreds of megs, and even gigabytes, when playing a game for a length of time. And making those calls to log messages can have a performance impact.

Logging only warnings/errors to a file by default likely wouldn't be too useful. Most issues that have needed the log needed a full trace (because even if a warning/error shows up, it may not be clear that's the cause of the problem without the extra traces). Plus, I don't know where the log file should go by default, since the folder with the executable or DLL isn't likely to be writable, and throwing it into some MyDocuments sub-folder would likely result in logs piling up the user doesn't even know are being made.

**Comment by mrmatteastwood** [comment]
Yeah, that makes sense :-/ Too bad!

**Comment by mirh** [comment]
Dsoal targets games that are far less likely to be digitally distributed, but at the same time they are far more probable to be ran as administrator too. 
I also wouldn't say it's rare for people to install games outside of C:\programfiles (especially if they aren't exactly using the original physical media). 

Anyhow we discussed that in #25, and it seemed a fair fallback if you can't write to the game folder could be either `%TMP%` or whatever in `%APPDATA%`. 

I didn't think to `DSOAL_LOGLEVEL` though.. But it seems the least of the problems (even because setting a global integer variable from [GUI](https://docs.oracle.com/en/database/oracle/machine-learning/oml4r/1.5.1/oread/creating-and-modifying-environment-variables-on-windows.html) or [CLI](https://ss64.com/nt/setx.html) looks a cakewalk compared to telling the user "decide some path"). 
If any you should rework the logic for loglevel=0 to mean "no log at all".
