### ISSUE TITLE
Splinter Cell games reverb problem

### ISSUE THREAD

**Issue by dzubei** [kcat/dsoal#72]
I`ve just tried DSOAL 1.4 (from nexusmods) in Splinter Cell, SC: Pandora Tommorow and SC: Chaos Theory. It sounds great but I noticed in all 3 games that there is some reverb added for Lambert and other characters voices and it shouldn`t be(SamFisher hears them in a earphones).  In previous version of DSOAL (1.31a) and in CreativeALchemy it works fine. Is this a known issue in a new version for some games? Is there any setting I should change to fix this?

**Comment by mirh** [comment]
"Between 1.31a and 1.4" hardly helps since it's like more than three years of updates. 
Try to find a smaller "range" with these: http://vaporeon.io/hosted/dsoal-builds/old/

**Comment by dzubei** [comment]
Thanks, I tried latest version and few previous ones from your link and all of them works without a hitch. So it seems that there is something wrong/different with a version on the nexusmods. I`ll stick with the latest version from the link. Could you tell me please if dsoal is good enough with default alsoft.ini or should I edit it to get more benefits and features?

**Comment by mirh** [comment]
Is there any difference if you delete the nexusmod alsoft.ini and just go with the default?
And how about with [this build](http://vaporeon.io/hosted/dsoal-builds/dsoal-r435.7z)?

**Comment by dzubei** [comment]
Thanks, I`ve done some tests.
1. in r430 there is no reverb for "character voices".
2. in r435 there is some reverb for "character voices" but it`s very subbtle and sounds natural. It`s nice.
3. in r435 with alsoft.ini from nexusmods it start to be much more vivid, loud and annoying, especially in SC1 i SCPT
4. nexusmods + default alsoft.ini gives same results as in 2.
So propably alsoft.ini from nexusmods it`s mainly set for Fallout3 and not necessary works perfect with other games.

**Comment by mirh** [comment]
So you are retracting your assessment that the builds from my first link are fine.. and I seem to understand you are pleased with the latest version. 
Is that correct? If this is the case then I'm not seeing other problems left to address.

**Comment by dzubei** [comment]
To be fair I`m a little bit confused now. The latest release sounds really nice and I'm pleased with it with default alsoft.ini. In the previous release, "character voices" sound same like through ALchemy softwere so I suppose r430 could be closer and more accurate to what we got on XP with SB soundcard. But I also read that ALchemy is broken so honestly I don`t know this is a good referance. Sorry for confusion and thank you for your help. No problems left to address. I`ll stick with the newest r435.

**Comment by mirh** [comment]
ALchemy may or may not represent a X-Fi with XP (particularly if you haven't done the `Using Creative Software 3D Library` fix), which in turn may or may not even be the same of an Audigy 2 with 2003 drivers. 
We did have other people checking out the game and doing comparisons though. 
A good reference should be the end of [this video](https://www.youtube.com/watch?v=nB9BTbtNyDw).

**Comment by dzubei** [comment]
Thanks, I`ll take a look on that.

**Comment by Paradise12314** [comment]
I know this issue could be considered fixed in a way, but I just wanted to drop a little thought in. If you download it from Nexusmods, I assume that they ship an altered alsoft.ini file with it. The Fallout games have a problem with Voices being very quiet with DSOAL and Xaudio-HRTF. So maybe Nexusmods amplify the Voice sounds to make them louder, which could explain why there was Reverb on Character voices in Splinter Cell. 

Always best to grab the Original Official DSOAL from Github and then change configs to suit the game. Just my theory :D

**Comment by dzubei** [comment]
Thanks for the info, actually I use DSOAL exactly that way recently, default one from Github. I also notcied that this kinda "reverb" on voices appears only when I set HRTF=true in alsoft.ini. I will definitely check new version of DSOAL when It`s avaiable :)

**Comment by Aerocatia** [comment]
The current build adds reverb to all voices in the game "Halo", even when they are not intended by the game.
I'm not sure what is meant to be happening here, since "Halo" has it's own set of issues.

**Comment by Aerocatia** [comment]
It seems an updated openal-soft can change reverb behavior, even with the same config.

**Comment by kcat** [comment]
The latest commits for OpenAL Soft and DSOAL should improve EAX behavior. Can you test to see if updated builds better match ALchemy (or real hardware) behavior?

**Comment by Aerocatia** [comment]
Win32 x86 build [here](http://vaporeon.io/hosted/dsoal-builds/dsoal-r441.7z).

**Comment by dzubei** [comment]
I did some tests today on SC1, SCPT and SCCT using r441. Everything sounds great by far, all the unwanted reverb for characters voices has disappeared. Thanks for this update. Now I can stealth again .`.

**Comment by mirh** [comment]
So presumably you can close the issue?

**Comment by dzubei** [comment]
Sure, problem solved, thanks.

**Comment by Hiradur** [comment]
At least for Splinter Cell: Double Agent, the problem is present again with the `c++-rewrite` branch, while it is not present with the `master` branch of DSOAL.

Logs: 
[scda_erroneous_eax_reverb_on_voices.zip](https://github.com/user-attachments/files/16352521/scda_erroneous_eax_reverb_on_voices.zip)

**Comment by kcat** [comment]
Looks like it's because `Buffer::AcquireResources` isn't implemented. On top of preparing DS8 effects (which are unimplemented, and the game doesn't seem to use anyway), it also selects hardware or software for locdefer buffers. On the rewrite, that returns an error so the game doesn't try to set EAX properties for the sound, leaving them at defaults so the effects apply (master branch implements it as long as it's only setting the buffer location and not doing any DS8 FX). It shouldn't be too hard to fix it when I get a moment to work on it.

**Comment by Hiradur** [comment]
Issue on the `c++-rewrite` branch appears to be fixed SC:DA with commit `e15e4fb81a791dfb2e86d128a82d966d5b6d350f`. Thanks for the quick reaction!
