### ISSUE TITLE
Wine - Autodetection of headphones not working

### ISSUE THREAD

**Issue by Hiradur** [kcat/dsoal#8]
If using DSOAL inside Wine (various Lutris builds) OpenAL Soft is unable to detect if headphones are connected on my system and thus doesn't enable HRTF when it should.

The autodetection works fine on the Ubuntu 18.04 base system and if a game running in Wine uses OpenAL natively (API calls are probably just passed through to the system's OpenAL Soft library).

Would it be possible to make the dsoal-aldrv.dll pass through the OpenAL calls as well? Replacing it with Wine's OpenAL32.dll only leads to a crash with error code 126 in the dsoal logfile.

This would have the benefit of having one single place for the OpenAL Soft library and the data and configuration files for HRTF and ambisonics.

**Comment by kcat** [comment]
Unfortunately Wine doesn't properly report the device form factor (headphones, headset, etc), and just defaults to physical speakers. So as far as DSOAL and any other app using WASAPI knows, Wine says it's on plain speakers and behaves accordingly. You can, however, create a config/ini file to tell OpenAL Soft to treat specific devices as headphones regardless of what Windows/Wine says it is.

Using pass-through calls for OpenAL isn't really much of an option since DSound needs to tie into the rest of the Windows audio system. That is to say, the same devices and GUIDs an app can discover through the WASAPI or WinMM APIs also needs to exist in DSound (and vice-versa). DSOAL currently accomplishes that probing WASAPI and using the device names and GUIDs it finds there with OpenAL, which only the Windows build of OpenAL Soft can recognize.

**Comment by Hiradur** [comment]
Thanks for the explanation. Maybe Wine can properly report the device form factor in the future.
